"""
Django settings for naturapeute project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    return [
        value.strip()
        for value in os.environ.get(name, default).split(",")
        if value.strip()
    ]


SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")

DEBUG = env_bool("DJANGO_DEBUG")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "*")
CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000",
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # custom
    'graphene_django',
    'django.contrib.postgres',
    'django_better_admin_arrayfield',
    'core',
    'corsheaders',
    'naturapeute',
    'blog',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "naturapeute"),
    }
}

for option, variable in {
    "USER": "POSTGRES_USER",
    "PASSWORD": "POSTGRES_PASSWORD",
    "HOST": "POSTGRES_HOST",
    "PORT": "POSTGRES_PORT",
}.items():
    value = os.environ.get(variable)
    if value:
        DATABASES["default"][option] = value


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Keep the existing AutoField-based schema stable when new models are added.
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

GRAPHENE = {
    'SCHEMA': 'api.graphql.schema' # Where your Graphene schema lives
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_ROOT = BASE_DIR / 'uploads'
MEDIA_URL = '/uploads/'

TEABLE_API_URL = os.environ.get("TEABLE_API_URL", "https://app.teable.ai")
TEABLE_BASE_ID = os.environ.get("TEABLE_BASE_ID", "")
TEABLE_API_TOKEN = os.environ.get("TEABLE_API_TOKEN", "")
try:
    TEABLE_CACHE_SECONDS = float(os.environ.get("TEABLE_CACHE_SECONDS", "60"))
except ValueError:
    TEABLE_CACHE_SECONDS = 60.0
TEABLE_ENABLED = env_bool(
    "TEABLE_ENABLED",
    bool(TEABLE_BASE_ID and TEABLE_API_TOKEN),
)

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "contact@naturapeute.ch")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
try:
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
except ValueError:
    EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
try:
    ACCOUNT_MAGIC_LINK_MAX_AGE = int(os.environ.get("ACCOUNT_MAGIC_LINK_MAX_AGE", "900"))
    ACCOUNT_MAGIC_LINK_COOLDOWN_SECONDS = int(
        os.environ.get("ACCOUNT_MAGIC_LINK_COOLDOWN_SECONDS", "60")
    )
except ValueError:
    ACCOUNT_MAGIC_LINK_MAX_AGE = 900
    ACCOUNT_MAGIC_LINK_COOLDOWN_SECONDS = 60

CORS_ORIGIN_ALLOW_ALL = True

try:
    from local_settings import *
except ImportError:
    pass
