"""Initial migration for the blog application.

Creates the Article and ArticleTag models with their fields and relationships.
"""

# Generated by Django 3.1.2 on 2020-11-25 09:12

from django.db import migrations, models
import blog.models


class Migration(migrations.Migration):
    """Initial migration class."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=(blog.models.Slugable, models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(
                    related_name='articles',
                    to='blog.ArticleTag'
                )),
            ],
            bases=(blog.models.Slugable, models.Model),
        ),
    ]
