"""Migration to add image field to Article model.

Adds an optional ImageField to store article images.
"""

# Generated by Django 3.1.2 on 2020-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class for adding image field to Article model."""

    dependencies = [
        ('blog', '0002_auto_20201126_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=''
            ),
        ),
    ]
