"""Migration to update Article model configuration.

Changes:
- Add default ordering by creation_date (newest first)
- Increase max_length of image field to 200 characters
"""

# Generated by Django 3.1.4 on 2020-12-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class for updating Article model configuration."""

    dependencies = [
        ('blog', '0003_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=''
            ),
        ),
    ]
