# Generated by Django 3.1.2 on 2020-11-24 18:49

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('words', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='office',
            name='latlng',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=2),
        ),
        migrations.AlterField(
            model_name='office',
            name='pictures',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.ImageField(upload_to=''), size=None),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='synonyms',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='agreements',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='languages',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=2), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='payment_types',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='socials',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
