# Generated by Django 3.1.2 on 2020-11-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0002_auto_20201124_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Synonyms',
            new_name='Synonym',
        ),
    ]
