# Generated by Django 3.1.2 on 2020-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0003_auto_20201124_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='therapist',
            name='membership',
            field=models.CharField(choices=[('invitee', 'Invité'), ('member', 'Membre'), ('premium', 'Payant')], default='member', max_length=20),
            preserve_default=False,
        ),
    ]
