# Generated by Django 3.1.2 on 2020-11-27 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import naturapeute.models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0004_auto_20201126_2025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='therapist',
            managers=[
                ('mixed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='office',
            name='pictures',
        ),
        migrations.CreateModel(
            name='OfficePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=naturapeute.models.OfficePicture.upload_to)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='naturapeute.office')),
            ],
        ),
    ]
