# Generated by Django 3.1.2 on 2020-11-28 10:03

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0005_auto_20201127_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='officepicture',
            name='uuid',
            field=models.CharField(default=core.utils.unique, max_length=12),
        ),
    ]
