# Generated by Django 3.1.2 on 2020-11-29 16:29

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0007_auto_20201129_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='socials',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
