# Generated by Django 3.1.2 on 2020-11-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0009_therapist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, related_name='therapists', to='naturapeute.Symptom'),
        ),
    ]
