# Generated by Django 3.1.2 on 2020-11-30 18:21

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0012_auto_20201130_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='languages',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('en', 'anglais'), ('fr', 'français'), ('de', 'allemand'), ('ru', 'russe'), ('it', 'italien'), ('es', 'espagnol')], max_length=2), blank=True, null=True, size=None),
        ),
    ]
