# Generated by Django 3.1.2 on 2020-11-30 19:06

from django.db import migrations, models
import naturapeute.models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0013_auto_20201130_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=naturapeute.models.Therapist.upload_to),
        ),
    ]
