# Generated by Django 3.1.2 on 2020-12-21 21:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    replaces = [('naturapeute', '0016_auto_20201212_1742'), ('naturapeute', '0017_auto_20201219_1943'), ('naturapeute', '0018_auto_20201219_1950'), ('naturapeute', '0019_auto_20201219_2029')]

    dependencies = [
        ('naturapeute', '0015_auto_20201130_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='services',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='therapist',
            name='invoice_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'author': {'city': '', 'email': '', 'iban': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}, 'hourly_price': 0, 'services': [], 'therapist': {'city': '', 'email': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}}, null=True),
        ),
    ]
