# Generated by Django 3.1.2 on 2020-12-12 17:42

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0015_auto_20201130_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='invoice_author_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'city': '', 'email': '', 'iban': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zip': ''}, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='invoice_therapist_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'city': '', 'email': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zip': ''}, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='services',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
