# Generated by Django 3.1.2 on 2020-12-19 19:43

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0016_auto_20201212_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='invoice_author_data',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='invoice_therapist_data',
        ),
        migrations.AddField(
            model_name='therapist',
            name='invoice_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'author': {'city': '', 'email': '', 'iban': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}, 'hourly_price': 0, 'therapist': {'city': '', 'email': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}}, null=True),
        ),
    ]
