# Generated by Django 3.1.2 on 2020-12-19 19:50

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0017_auto_20201219_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='invoice_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'author': {'city': '', 'email': '', 'iban': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}, 'hourly_price': 0, 'services': [], 'therapist': {'city': '', 'email': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}}, null=True),
        ),
    ]
