# Generated by Django 3.1.2 on 2020-12-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0019_auto_20201219_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('man', 'Homme'), ('woman', 'Femme')], max_length=6, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('canton', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.IntegerField(blank=True, max_length=4, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naturapeute.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naturapeute.therapist')),
            ],
        ),
        migrations.AddField(
            model_name='therapist',
            name='patients',
            field=models.ManyToManyField(related_name='therapists', through='naturapeute.TherapistPatient', to='naturapeute.Patient'),
        ),
    ]
