# Generated by Django 3.1.2 on 2020-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0020_auto_20201221_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
