# Generated by Django 3.1.2 on 2020-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0021_auto_20201221_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='invoice_data',
            field=models.JSONField(default={'author': {'city': '', 'email': '', 'iban': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}, 'hourly_price': 0, 'services': [], 'therapist': {'city': '', 'email': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}}, null=True),
        ),
    ]
