# Generated by Django 3.1.2 on 2020-12-22 10:04

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0022_auto_20201221_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='invoice_data',
            field=models.JSONField(blank=True, default={'author': {'city': '', 'email': '', 'iban': '', 'name': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}, 'hourly_price': 0, 'services': [], 'therapist': {'city': '', 'email': '', 'firstname': '', 'lastname': '', 'phone': '', 'rcc': '', 'street': '', 'zipcode': ''}}, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='services',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
