# Generated by Django 3.1.4 on 2020-12-24 17:10

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0024_auto_20201222_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='languages',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('en', 'anglais'), ('fr', 'français'), ('de', 'allemand'), ('ru', 'russe'), ('it', 'italien'), ('es', 'espagnol'), ('nl', 'néerlandais'), ('pl', 'polonais')], max_length=2), blank=True, null=True, size=None),
        ),
    ]
