# Generated by Django 3.1.4 on 2021-01-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0025_auto_20201224_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
