# Generated by Django 3.1.4 on 2021-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0026_auto_20210103_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
