# Generated by Django 3.2.5 on 2021-12-21 21:25

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0027_patient_street2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='languages',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('en', 'anglais'), ('fr', 'français'), ('de', 'allemand'), ('ru', 'russe'), ('it', 'italien'), ('es', 'espagnol'), ('nl', 'néerlandais'), ('pl', 'polonais'), ('pt', 'portugais'), ('ro', 'roumain')], max_length=2), blank=True, null=True, size=None),
        ),
    ]
