# Generated by Django 5.1.4 on 2025-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturapeute', '0031_merge_20250116_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='URL Calendly du thérapeute', max_length=255, null=True),
        ),
    ]
